### ISSUE TITLE
Dictionary and vocab generation

### ISSUE THREAD

**Issue by SiddharthGadekar** [vsymbol/CUTIE#12]
Hello,

Can you please explain how the dictionary and vocab is generated and the steps to replicate for a different dataset?
Is the vocab.txt file pre-existing or is it generated through the program?

**Comment by SiddharthGadekar** [comment]
Oh okay, my understanding is that the vocab.txt is the one for BERT. Can you please confirm on the steps to be replicated for a different dataset?

**Comment by muralimariyappan** [comment]
The vocab.txt is not generated by the program.  But the other files *_classes.npy, *_dictionary.npy, *_word_to_index.npy and *_index_to_word.npy are generated by the main_data_loader.py file

The _dress_text function uses the vocab.txt to look for known words and uses it for word piece tokenization.  Refer BERT model.
You can add the words that you want to be included in your output in vocab.txt manually or through some scripts.
To create dictionary from training data, you can simply execute the main_dict_json.py file.  You may have to configure the parameters to accommodate your input though, but the default one works too.

**Comment by SiddharthGadekar** [comment]
Thanks a lot
